#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

changed() {
  git diff --name-only HEAD@{1} HEAD | grep "^$1" > /dev/null 2>&1
}

if changed 'package-lock.json'; then
  echo "package-lock.json has changed. Running npm install to bring your dependencies up to date."
  npm install
fi
